# Generated by Django 6.0 on 2026-07-06 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_department_organization_designation_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="aadhaar_card",
            field=models.FileField(
                blank=True,
                upload_to="aadhaar_cards/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="appointment_letter",
            field=models.FileField(
                blank=True,
                upload_to="appointment_letters/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="offer_letter",
            field=models.FileField(
                blank=True,
                upload_to="offer_letters/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="pan_card",
            field=models.FileField(
                blank=True,
                upload_to="pan_cards/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                upload_to="profile_imgs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="resume",
            field=models.FileField(
                blank=True,
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
