# Generated by Django 6.0 on 2026-08-26 05:40

import django.core.validators
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_aadhaar_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="aadhaar_card",
            field=models.FileField(
                blank=True,
                upload_to=employees.models.aadhaar_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="appointment_letter",
            field=models.FileField(
                blank=True,
                upload_to=employees.models.appointment_letter_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="offer_letter",
            field=models.FileField(
                blank=True,
                upload_to=employees.models.offer_letter_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="pan_card",
            field=models.FileField(
                blank=True,
                upload_to=employees.models.pan_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="resume",
            field=models.FileField(
                blank=True,
                upload_to=employees.models.resume_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
