# Generated by Django 6.0 on 2026-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="If True, user must create a new password before accessing the system.",
            ),
        ),
    ]
