# Generated by Django 6.0 on 2026-06-02 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_customuser_is_approved"),
        ("employees", "0003_department_organization_designation_organization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JoiningLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("letter_number", models.CharField(db_index=True, max_length=30)),
                ("candidate_name", models.CharField(max_length=160)),
                ("candidate_email", models.EmailField(blank=True, max_length=254)),
                ("candidate_phone", models.CharField(blank=True, max_length=20)),
                ("issue_date", models.DateField()),
                ("joining_date", models.DateField()),
                ("employment_type", models.CharField(blank=True, max_length=40)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("designation", models.CharField(blank=True, max_length=120)),
                ("work_location", models.CharField(blank=True, max_length=140)),
                ("reporting_manager", models.CharField(blank=True, max_length=140)),
                (
                    "annual_ctc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "probation_period",
                    models.CharField(
                        blank=True, default="As per company policy", max_length=80
                    ),
                ),
                ("subject", models.CharField(default="Joining Letter", max_length=220)),
                ("body", models.TextField(blank=True)),
                (
                    "signature_name",
                    models.CharField(
                        blank=True, default="HR Department", max_length=140
                    ),
                ),
                (
                    "signature_title",
                    models.CharField(
                        blank=True, default="Human Resources", max_length=140
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("ACCEPTED", "Accepted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="joining_letters",
                        to="employees.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "letter_number"],
                        name="joining_let_organiz_7f25b5_idx",
                    ),
                    models.Index(
                        fields=["organization", "joining_date"],
                        name="joining_let_organiz_1560c0_idx",
                    ),
                    models.Index(
                        fields=["status"], name="joining_let_status_6ed65f_idx"
                    ),
                ],
                "unique_together": {("organization", "letter_number")},
            },
        ),
    ]
