# Generated by Django 6.0 on 2026-06-03 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_approved"),
        ("employees", "0003_department_organization_designation_organization_and_more"),
        ("joining_letters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="joiningletter",
            name="letter_type",
            field=models.CharField(
                choices=[("OFFER", "Offer Letter")],
                db_index=True,
                default="OFFER",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="joiningletter",
            name="subject",
            field=models.CharField(default="Offer Letter", max_length=220),
        ),
        migrations.AddIndex(
            model_name="joiningletter",
            index=models.Index(
                fields=["organization", "letter_type"],
                name="joining_let_organiz_26230c_idx",
            ),
        ),
    ]
