# Generated by Django 6.0 on 2026-06-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("joining_letters", "0002_joiningletter_letter_type_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="joiningletter",
            new_name="letters_let_organiz_2ff5cf_idx",
            old_name="joining_let_organiz_7f25b5_idx",
        ),
        migrations.RenameIndex(
            model_name="joiningletter",
            new_name="letters_let_organiz_08ea65_idx",
            old_name="joining_let_organiz_1560c0_idx",
        ),
        migrations.RenameIndex(
            model_name="joiningletter",
            new_name="letters_let_organiz_95375c_idx",
            old_name="joining_let_organiz_26230c_idx",
        ),
        migrations.RenameIndex(
            model_name="joiningletter",
            new_name="letters_let_status_a9a39d_idx",
            old_name="joining_let_status_6ed65f_idx",
        ),
        migrations.AlterModelTable(
            name="joiningletter",
            table="letters_letter",
        ),
    ]
