# Generated by Django 6.0 on 2026-06-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "joining_letters",
            "0003_rename_joining_let_organiz_7f25b5_idx_letters_let_organiz_2ff5cf_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="joiningletter",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("OFFER", "Offer Letter"),
                    ("APPOINTMENT", "Appointment Letter"),
                ],
                db_index=True,
                default="OFFER",
                max_length=30,
            ),
        ),
    ]
