# Generated by Django 6.0 on 2026-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joining_letters", "0007_add_additional_letter_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="joiningletter",
            name="custom_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="joiningletter",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("OFFER", "Offer Letter"),
                    ("APPOINTMENT", "Appointment Letter"),
                    ("JOINING", "Joining Letter"),
                    ("CONFIRMATION", "Confirmation Letter"),
                    ("PROMOTION", "Promotion Letter"),
                    ("EXPERIENCE", "Experience Letter"),
                    ("RELIEVING", "Relieving Letter"),
                    ("WARNING", "Warning Letter"),
                    ("CUSTOM", "Custom Letter"),
                ],
                db_index=True,
                default="OFFER",
                max_length=30,
            ),
        ),
    ]
