# Generated by Django 6.0 on 2026-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("LEAVE", "Leave Update"),
                    ("ATTENDANCE", "Attendance Update"),
                    ("SYSTEM", "System Alert"),
                    ("LOAN", "Loan Update"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
