# Generated by Django 6.0 on 2026-05-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0003_enterprise_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holiday",
            name="location",
        ),
        migrations.RemoveField(
            model_name="leavebalance",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="leavebalance",
            name="used",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="current_handler",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="accrual_rate",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="carry_forward_limit",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="min_days_before_apply",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="requires_attachment",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="total_days_per_year",
        ),
        migrations.AlterField(
            model_name="leaveaccruallog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="leavepolicy",
            name="attachment_threshold_days",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Attachment required if leave duration exceeds this",
            ),
        ),
        migrations.AlterField(
            model_name="leavepolicy",
            name="min_service_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Days of employment required before this leave can be used",
            ),
        ),
        migrations.AlterField(
            model_name="leavepolicy",
            name="sandwich_rule",
            field=models.BooleanField(
                default=False,
                help_text="If True, holidays/weekends falling between leave days are counted as leave",
            ),
        ),
        migrations.DeleteModel(
            name="LeaveApprovalLog",
        ),
    ]
