# Generated by Django 6.0 on 2026-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0006_alter_leaveaccruallog_action_type_compoffrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("FULL", "Full Day"),
                    ("MORNING", "First Half"),
                    ("AFTERNOON", "Second Half"),
                    ("SHORT", "Short Leave (2 Hours)"),
                ],
                default="FULL",
                max_length=10,
            ),
        ),
    ]
