# Generated by Django 6.0 on 2026-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0007_alter_leaverequest_session_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
