# Generated by Django 6.0 on 2026-05-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0010_approvalworkflow_approver_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveaccruallog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("ACCRUAL", "Automated Accrual"),
                    ("MANUAL", "Manual Adjustment"),
                    ("CARRY_FORWARD", "Year-end Carry Forward"),
                    ("ENCASHMENT", "Leave Encashment"),
                    ("COMP_OFF_CREDIT", "Comp-off Credit"),
                    ("LEAVE_CANCEL_CREDIT", "Leave Cancellation Credit"),
                    ("LAPSED", "Lapsed Leaves"),
                ],
                max_length=20,
            ),
        ),
    ]
