# Generated by Django 6.0 on 2026-07-06 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0012_alter_leavetype_options_holiday_holiday_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveattachment",
            name="file",
            field=models.FileField(
                upload_to="leave_attachments/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="leave_attachments/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
