# Generated by Django 6.0 on 2026-05-20 11:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_employeetaxdeclaration_declarationworkflowlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeetaxprofile",
            name="annual_ctc",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="employeetaxprofile",
            name="basic_salary",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="employeetaxprofile",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="employeetaxprofile",
            name="hra",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="employeetaxprofile",
            name="landlord_pan",
            field=models.CharField(
                blank=True,
                help_text="Required if annual rent > ₹1,00,000",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employeetaxprofile",
            name="other_income",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="employeetaxprofile",
            name="rent_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="employeetaxprofile",
            name="special_allowance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="employeetaxprofile",
            name="variable_pay",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
    ]
