# Generated by Django 6.0 on 2026-05-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_employeetaxprofile_annual_ctc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declarationworkflowlog",
            name="declaration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="payroll.employeetaxdeclaration",
            ),
        ),
    ]
