# Generated by Django 6.0 on 2026-05-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_alter_declarationworkflowlog_declaration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investmentproof",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="investmentproof",
            name="declaration",
        ),
        migrations.RemoveField(
            model_name="investmentproof",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="investmentproof",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="investmentproof",
            name="updated_by",
        ),
        migrations.RemoveConstraint(
            model_name="taxdeclaration",
            name="uq_taxdeclaration_emp_fy",
        ),
        migrations.DeleteModel(
            name="InvestmentProof",
        ),
        migrations.DeleteModel(
            name="TaxDeclaration",
        ),
    ]
