# Generated by Django 6.0 on 2026-07-06 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_remove_investmentproof_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declarationproof",
            name="file",
            field=models.FileField(
                upload_to="tax_proofs/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
