# Generated by Django 6.0 on 2026-05-23 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_customuser_is_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMPANY_NEWS", "Company News"),
                            ("POLICY", "Policy"),
                            ("EVENT", "Event"),
                            ("HR_UPDATE", "HR Update"),
                            ("OPERATIONS", "Operations"),
                        ],
                        default="COMPANY_NEWS",
                        max_length=30,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "All Employees"),
                            ("EMPLOYEES", "Employees Only"),
                            ("STAFF", "Staff Only"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(default="HR Department", max_length=80),
                ),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField()),
                ("is_pinned", models.BooleanField(db_index=True, default=False)),
                (
                    "publish_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-publish_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "organization",
                            "is_active",
                            "is_deleted",
                            "publish_at",
                        ],
                        name="announcemen_organiz_6028a2_idx",
                    ),
                    models.Index(
                        fields=["organization", "audience", "category"],
                        name="announcemen_organiz_975d28_idx",
                    ),
                ],
            },
        ),
    ]
