# Generated by Django 6.0 on 2026-05-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="early_out_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
