# Generated by Django 6.0 on 2026-09-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_location_apply_to_and_selected_employees"),
        ("employees", "0005_alter_employee_aadhaar_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesettings",
            name="location_apply_to",
            field=models.CharField(
                choices=[("all", "All Employees"), ("selected", "Selected Employees")],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="attendancesettings",
            name="location_restricted_employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Employees subject to GPS location validation when Apply To = Selected Employees.",
                related_name="location_restricted_settings",
                to="employees.employee",
            ),
        ),
    ]
