# Generated by Django 6.0 on 2026-09-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_alter_attendancesettings_location_apply_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesettings",
            name="sandwich_leave_policy",
            field=models.BooleanField(default=False),
        ),
    ]
